apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fbqi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-fbqi@sha256:54380809a199a49af102e29769e26cb80cb5fa30c44e9226ab133c1685f8a0e7
        name: my-nodejs
        resources: {}
status: {}
